//(function() {
//    
//    angular 
//        .module('scorecardMod')
//        .run(function(boxState) {
//            for (var i=0; i<11; i++) {
//               for(var j=0; j<11; j++) {
//                    boxState.little[i][j].status = 'initial';
//
//                    boxState.little[i][j].first = null;
//                    boxState.little[i][j].second = null;
//                    boxState.little[i][j].third = null;
//                    boxState.little[i][j].home = null;
//
//                    boxState.little[i][j].toFirst = false;
//                    boxState.little[i][j].toSecond = false; 
//                    boxState.little[i][j].toThird = false;   
//                    boxState.little[i][j].toHome = false;
//
//                    boxState.little[i][j].advFrmFirst = false;
//                    boxState.little[i][j].advFrmSecond = false;
//                    boxState.little[i][j].advFrmThird = false;
//
//                    boxState.little[i][j].oneOut = null;
//                    boxState.little[i][j].twoOut = null;
//                    boxState.little[i][j].threeOut = null;              
//               }        
//            }
//    });
//    
//    })();
 
(function() {
    
    angular 
        .module('scorecardMod')
       
        .value('boxState', 
        // state will have value for little box:  at-bat, on-base and big box:  initial, on-base and out.   
            {
            'littleHome': [
              [{status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}],
               
              [{status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}],
               
               [{status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}],
               
               [{status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}],
               
              [{status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}],
               
               [{status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}],
               
               [{status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}],
               
              [{status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}],
               
               [{status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}]
          ],
            
           'littleVisitors': [
              [{status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}],
               
              [{status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}],
               
               [{status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}],
               
               [{status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}],
               
              [{status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}],
               
               [{status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}],
               
               [{status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}],
               
              [{status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}],
               
               [{status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}, {status: 'initial', first: null, second: null, third: null, home: null, toFirst: false, toSecond: false, toThird: false, advFrmFirst: false, advFrmSecond: false, advFromThird: false, oneOut: null, twoOut: null, threeOut: null, fieldBackground: "grey"}]
          ],
            
//want to track whether a box was AB, PA, 1, 2, 3, HR, BB, E, WP, PB, RBI, SB, R, ER, SAC, K.
            
//Will need this object for each little box => {AB: 0, PA: 0, Single: 0, Double: 0, Triple: 0, HR: 0, BB: 0, E: 0, WP: 0, PB: 0, RBI: 0, SB: 0, R: 0, ER: 0, SAC: 0, K: 0}

//Created an initialized when the litteBox first hit in initial state.
            
          'homeRawStats': [[], 
                           [], 
                           [], 
                           [], 
                           [], 
                           [], 
                           [], 
                           [], 
                           []
              
          ],
          
            
          'visitorsRawStats': [[], 
                               [], 
                               [], 
                               [], 
                               [], 
                               [], 
                               [], 
                               [], 
                               []
              
          ],

           'big': [
              ['initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial'],
              ['initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial'],
              ['initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial'],
              ['initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial'],
              ['initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial'],
              ['initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial'],
              ['initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial'],
              ['initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial'],
              ['initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial', 'initial']            
          ]
             
          
        
        }
            );
})();



                
                

